Repository Travel-Makerdd/Travel-Maker-BE, pull requests merged in 2024-12, with the labels that each got.

#75 ✨ FEAT. CORS 설정
  src/main/java/com/hsu/travelmaker/global/security/config/SecurityConfig.java
Labels: 🪐jungeun, ✨feat

#77 🎨 CHORE. 로그인시 닉네임 반환
  src/main/java/com/hsu/travelmaker/domain/user/service/UserServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/user/web/dto/SignInResponseDto.java
Labels: 🪐jungeun, ✨feat

#79 ✨FEAT. 여행지 테이블 생성
  src/main/java/com/hsu/travelmaker/domain/destination/entity/Destination.java
  src/main/java/com/hsu/travelmaker/domain/destination/entity/DestinationImage.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/controller/TripController.java
Labels: 👑min, ✨feat

#81 🎨CHORE. 여행상품 이미지 저장경로 수정
  src/main/java/com/hsu/travelmaker/domain/activity/web/dto/ActivityResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/dto/ReservationResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/schedule/web/dto/ScheduleResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/trip/entity/Trip.java
  src/main/java/com/hsu/travelmaker/domain/trip/entity/TripImage.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripService.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/controller/TripController.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripCreateDto.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripResponseDto.java
Labels: 👑min

#85 ✨FEAT. 여행지 조회 api 개발
  src/main/java/com/hsu/travelmaker/domain/destination/entity/Destination.java
  src/main/java/com/hsu/travelmaker/domain/destination/entity/DestinationImage.java
  src/main/java/com/hsu/travelmaker/domain/destination/repository/DestinationImageRepository.java
  src/main/java/com/hsu/travelmaker/domain/destination/repository/DestinationRepository.java
  src/main/java/com/hsu/travelmaker/domain/destination/service/DestinationService.java
  src/main/java/com/hsu/travelmaker/domain/destination/service/DestinationServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/destination/web/controller/DestinationController.java
  src/main/java/com/hsu/travelmaker/domain/destination/web/dto/DestinationResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/resources/images/bangkok.jpg
  src/main/resources/images/busan.jpg
  src/main/resources/images/california.jpg
  src/main/resources/images/honkong.jpg
  src/main/resources/images/newyork.jpg
  src/main/resources/images/osaka.jpg
  src/main/resources/images/seoul.jpg
  src/main/resources/images/shanghai.jpg
  src/main/resources/images/singapore.jpg
  src/main/resources/images/sydney.jpg
  src/main/resources/images/taipei.jpg
  src/main/resources/images/tokyo.jpg
Labels: 👑min, ✨feat

#87 🎨 CHORE. 게시글 이미지 경로 및 조회 수정
  src/main/java/com/hsu/travelmaker/domain/post/entity/PostImage.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostService.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/post/web/controller/PostController.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostListResponseDto.java
Labels: 🪐jungeun, ✨feat

#89 🎨CHORE. 리뷰 작성시 예약한 사용자 검증 추가
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewServiceImpl.java
Labels: 👑min

#91 🎨CHORE. 여행상품 즐겨찾기 여부 반환
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripResponseDto.java
Labels: 👑min

#93 🗃️ADD. 여행지 관련 SQL 스크립트 추가
  src/sql/seed-destination.sql
Labels: 👑min

#95 📝DOCS. README에 데이터베이스 초기화 방법 추가
  README.md
Labels: 👑min

#96 📄DOCS. README에 SQL 스크립트 파일명 수정
  README.md
Labels: 👑min
