Repository Travel-Makerdd/Travel-Maker-BE, pull requests merged in 2024-11, with the labels that each got.

#3 ✨ FEAT. JWT 회원가입
  build.gradle
  src/main/java/com/hsu/travelmaker/domain/user/entity/User.java
  src/main/java/com/hsu/travelmaker/domain/user/repository/UserRepository.java
  src/main/java/com/hsu/travelmaker/domain/user/service/UserService.java
  src/main/java/com/hsu/travelmaker/domain/user/service/UserServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/user/web/controller/UserController.java
  src/main/java/com/hsu/travelmaker/domain/user/web/dto/SignUpDto.java
  src/main/java/com/hsu/travelmaker/global/controller/CustomErrorController.java
  src/main/java/com/hsu/travelmaker/global/security/config/SecurityConfig.java
  src/main/java/com/hsu/travelmaker/global/security/jwt/filter/JwtTokenFilter.java
  src/main/java/com/hsu/travelmaker/global/security/jwt/util/JwtTokenProvider.java
  src/main/java/com/hsu/travelmaker/global/security/service/MyUserDetails.java
Labels: 🪐jungeun, ✨feat

#7 ✨ FEAT. 프로필 생성
  src/main/java/com/hsu/travelmaker/domain/profile/entity/Profile.java
  src/main/java/com/hsu/travelmaker/domain/profile/entity/Role.java
  src/main/java/com/hsu/travelmaker/domain/profile/repository/ProfileRepository.java
  src/main/java/com/hsu/travelmaker/domain/profile/service/ProfileService.java
  src/main/java/com/hsu/travelmaker/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/profile/web/controller/ProfileController.java
  src/main/java/com/hsu/travelmaker/domain/profile/web/dto/ProfileUpdateDto.java
  src/main/java/com/hsu/travelmaker/domain/user/service/UserServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/user/web/controller/UserController.java
  src/main/java/com/hsu/travelmaker/global/security/config/SecurityConfig.java
  src/main/java/com/hsu/travelmaker/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/hsu/travelmaker/global/security/jwt/filter/JwtTokenFilter.java
  src/main/java/com/hsu/travelmaker/global/security/jwt/util/AuthenticationUserUtils.java
Labels: 🪐jungeun, ✨feat

#8 ✨ FEAT. 프로필 조회
  src/main/java/com/hsu/travelmaker/domain/profile/service/ProfileService.java
  src/main/java/com/hsu/travelmaker/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/profile/web/controller/ProfileController.java
  src/main/java/com/hsu/travelmaker/domain/profile/web/dto/ProfileCheckDto.java
Labels: 🪐jungeun, ✨feat

#11 ✨ FEAT. 게시글 생성
  src/main/java/com/hsu/travelmaker/domain/post/entity/Post.java
  src/main/java/com/hsu/travelmaker/domain/post/entity/PostImage.java
  src/main/java/com/hsu/travelmaker/domain/post/repository/PostImageRepository.java
  src/main/java/com/hsu/travelmaker/domain/post/repository/PostRepository.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostService.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/post/web/controller/PostController.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostCreateDto.java
  src/main/java/com/hsu/travelmaker/domain/profile/repository/ProfileRepository.java
  src/main/java/com/hsu/travelmaker/domain/profile/service/ProfileServiceImpl.java
Labels: 🪐jungeun, ✨feat

#14 ✨ FEAT. 게시글 조회
  src/main/java/com/hsu/travelmaker/domain/post/repository/PostImageRepository.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostService.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/post/web/controller/PostController.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostResponseDto.java
Labels: 🪐jungeun, ✨feat

#20 ✨FEAT. 여행상품 전체 조회
  src/main/java/com/hsu/travelmaker/domain/trip/repository/TripRepository.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripService.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/controller/TripController.java
Labels: 👑min, ✨feat

#21 ✨Feat. 여행상품 상세 조회
  src/main/java/com/hsu/travelmaker/domain/trip/repository/TripRepository.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripService.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/controller/TripController.java
Labels: 👑min, ✨feat

#27 ✨CHORE. 여행상품 등록 및 조회 수정
  src/main/java/com/hsu/travelmaker/domain/trip/entity/Trip.java
  src/main/java/com/hsu/travelmaker/domain/trip/entity/TripImage.java
  src/main/java/com/hsu/travelmaker/domain/trip/repository/TripImageRepository.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripCreateDto.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripResponseDto.java
Labels: 👑min

#28 ✨FEAT. 일정조회 기능 구현
  src/main/java/com/hsu/travelmaker/domain/activity/entity/Activity.java
  src/main/java/com/hsu/travelmaker/domain/activity/repository/ActivityRepository.java
  src/main/java/com/hsu/travelmaker/domain/activity/service/ActivityService.java
  src/main/java/com/hsu/travelmaker/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/activity/web/dto/ActivityResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/schedule/entity/Schedule.java
  src/main/java/com/hsu/travelmaker/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/hsu/travelmaker/domain/schedule/service/ScheduleService.java
  src/main/java/com/hsu/travelmaker/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/schedule/web/controller/ScheduleController.java
  src/main/java/com/hsu/travelmaker/domain/schedule/web/dto/ScheduleResponseDto.java
Labels: 👑min, ✨feat

#30 ✨FIX. import 오류 수정
  src/main/java/com/hsu/travelmaker/domain/activity/entity/Activity.java
  src/main/java/com/hsu/travelmaker/domain/activity/repository/ActivityRepository.java
  src/main/java/com/hsu/travelmaker/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/schedule/entity/Schedule.java
  src/main/java/com/hsu/travelmaker/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/hsu/travelmaker/domain/schedule/service/ScheduleService.java
  src/main/java/com/hsu/travelmaker/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/schedule/web/controller/ScheduleController.java
  src/main/java/com/hsu/travelmaker/domain/schedule/web/dto/ScheduleResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/trip/entity/Trip.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripCreateDto.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/dto/TripResponseDto.java
Labels: 👑min

#31 ✨Feat. 여행상품 즐겨찾기 기능 구현
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/entity/TripFavorite.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/repository/TripFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteService.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/controller/TripFavoriteController.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/dto/TripFavoriteCreateDto.java
Labels: 👑min, ✨feat

#32 ✨Feat. 여행상품 즐겨찾기 해제 기능 구현
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/repository/TripFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteService.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/controller/TripFavoriteController.java
Labels: 👑min, ✨feat

#33 ✨FEAT. 여행상품 즐겨찾기 조회
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteService.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/controller/TripFavoriteController.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/dto/TripFavoriteRemoveDto.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/dto/TripFavoriteResponseDto.java
Labels: 👑min, ✨feat

#39 🛠️CHORE. 여행상품 즐겨찾기 수정
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/entity/TripFavorite.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/repository/TripFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/controller/TripFavoriteController.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/dto/TripFavoriteResponseDto.java
Labels: 👑min

#40 ✨FEAT. 예약 생성 기능 구현
  src/main/java/com/hsu/travelmaker/domain/reservation/entity/Reservation.java
  src/main/java/com/hsu/travelmaker/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationService.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/controller/ReservationController.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/dto/ReservationCreateDto.java
Labels: 👑min, ✨feat

#41 ✨FEAT. 예약 취소 기능 구현
  src/main/java/com/hsu/travelmaker/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationService.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/controller/ReservationController.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/dto/ReservationDeleteDto.java
Labels: 👑min, ✨feat

#42 ✨FEAT. 예약목록 조회 기능 구현
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationService.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/controller/ReservationController.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/dto/ReservationResponseDto.java
Labels: 👑min, ✨feat

#44 ✨FEAT. 리뷰 생성
  src/main/java/com/hsu/travelmaker/domain/review/entity/Review.java
  src/main/java/com/hsu/travelmaker/domain/review/repository/ReviewRepository.java
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewService.java
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/review/web/controller/ReviewController.java
  src/main/java/com/hsu/travelmaker/domain/review/web/dto/ReviewCreateDto.java
Labels: 👑min, ✨feat

#45 ✨FEAT. 여행상품 리뷰 조회
  src/main/java/com/hsu/travelmaker/domain/review/repository/ReviewRepository.java
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewService.java
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/review/web/controller/ReviewController.java
  src/main/java/com/hsu/travelmaker/domain/review/web/dto/ReviewResponseDto.java
Labels: 👑min, ✨feat

#47 ✨FEAT. 사용자 리뷰 목록 조회
  src/main/java/com/hsu/travelmaker/domain/review/repository/ReviewRepository.java
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewService.java
  src/main/java/com/hsu/travelmaker/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/review/web/controller/ReviewController.java
Labels: 👑min, ✨feat

#48 ✨ FEAT. 회원 탈퇴
  src/main/java/com/hsu/travelmaker/domain/post/repository/PostRepository.java
  src/main/java/com/hsu/travelmaker/domain/profile/entity/Profile.java
  src/main/java/com/hsu/travelmaker/domain/profile/repository/ProfileRepository.java
  src/main/java/com/hsu/travelmaker/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/entity/Trip.java
  src/main/java/com/hsu/travelmaker/domain/trip/repository/TripRepository.java
  src/main/java/com/hsu/travelmaker/domain/trip/service/TripServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/trip/web/controller/TripController.java
  src/main/java/com/hsu/travelmaker/domain/user/entity/User.java
  src/main/java/com/hsu/travelmaker/domain/user/repository/UserRepository.java
  src/main/java/com/hsu/travelmaker/domain/user/service/UserService.java
  src/main/java/com/hsu/travelmaker/domain/user/service/UserServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/user/web/controller/UserController.java
Labels: 🪐jungeun, ✨feat

#53 ✨ FEAT. 게시글 목록 조회
  src/main/java/com/hsu/travelmaker/domain/post/repository/PostImageRepository.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostService.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/post/web/controller/PostController.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostListPageResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostListResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/user/entity/User.java
Labels: 🪐jungeun, ✨feat

#54 Feat/#50 post favorite
  src/main/java/com/hsu/travelmaker/domain/post/web/controller/PostController.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/entity/PostFavorite.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/repository/PostFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/service/PostFavoriteService.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/service/PostFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/web/controller/PostFavoriteController.java
Labels: 🪐jungeun, ✨feat

#57 ✨ FEAT. 게시글 즐겨찾기 해제
  src/main/java/com/hsu/travelmaker/domain/postfavorite/repository/PostFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/service/PostFavoriteService.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/service/PostFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/web/controller/PostFavoriteController.java
Labels: 🪐jungeun, ✨feat

#58 ✨ FEAT. 게시글 즐겨찾기 조회
  src/main/java/com/hsu/travelmaker/domain/postfavorite/repository/PostFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/service/PostFavoriteService.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/service/PostFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/web/controller/PostFavoriteController.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/web/dto/PostFavoriteResponseDto.java
Labels: 🪐jungeun, ✨feat

#60 ✨ FEAT. 게시글 수정
  src/main/java/com/hsu/travelmaker/domain/post/repository/PostImageRepository.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostService.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/post/web/controller/PostController.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostUpdateDto.java
Labels: 🪐jungeun, ✨feat

#65 🔨CHORE. 여행상품 즐겨찾기 수정
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/repository/TripFavoriteRepository.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/controller/TripFavoriteController.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/web/dto/TripFavoriteCreateDto.java
Labels: 👑min

#66 ✨ FEAT. 댓글 조회
  src/main/java/com/hsu/travelmaker/domain/comment/repository/CommentRepository.java
  src/main/java/com/hsu/travelmaker/domain/comment/service/CommentService.java
  src/main/java/com/hsu/travelmaker/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/comment/web/controller/CommentController.java
  src/main/java/com/hsu/travelmaker/domain/comment/web/dto/CommentResponseDto.java
Labels: 🪐jungeun, ✨feat

#69 🔨CHORE. 예약 생성 수정
  src/main/java/com/hsu/travelmaker/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/controller/ReservationController.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/dto/ReservationCreateDto.java
Labels: 👑min

#70 🔨CHORE. 예약 삭제 수정
  src/main/java/com/hsu/travelmaker/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/controller/ReservationController.java
  src/main/java/com/hsu/travelmaker/domain/reservation/web/dto/ReservationDeleteDto.java
Labels: 👑min

#71 🔨CHORE. 여행상품 즐겨찾기 해제 수정
  src/main/java/com/hsu/travelmaker/domain/reservation/service/ReservationService.java
  src/main/java/com/hsu/travelmaker/domain/tripfavorite/service/TripFavoriteService.java
Labels: 👑min

#73 🎨 CHORE. 게시글 목록 조회시 댓글, 즐겨찾기 수 반환
  src/main/java/com/hsu/travelmaker/domain/comment/repository/CommentRepository.java
  src/main/java/com/hsu/travelmaker/domain/post/service/PostServiceImpl.java
  src/main/java/com/hsu/travelmaker/domain/post/web/dto/PostListResponseDto.java
  src/main/java/com/hsu/travelmaker/domain/postfavorite/repository/PostFavoriteRepository.java
Labels: 🪐jungeun
